// <auto-generated />
namespace Fivet2Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlertaAlterColumnHoraNotif : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlertaAlterColumnHoraNotif));
        
        string IMigrationMetadata.Id
        {
            get { return "201702101442195_AlertaAlterColumnHoraNotif"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
